---
pipeline:
  docker:
    image: plugins/docker
    secrets:
      - docker_password

    email: kevin.bacon@mail.com

    username: tonglil
    repo: tonglil/drone-labeler
    tags:
      - latest

    when:
      branch: master
      event: push

  docker:
    image: plugins/docker
    secrets:
      - docker_password

    email: kevin.bacon@mail.com

    username: tonglil
    repo: tonglil/drone-labeler
    tags:
      - stable
      - "${DRONE_TAG}"

    when:
      event: tag
